name: surface_3d_chart_example
description: Example app showing 2D and 3D charts built with the flutter_charts_kit package.
publish_to: none
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_charts_kit:
    path: ../

flutter:
  uses-material-design: true
